name 'bweiss-clamav'
version '0.1.1'
author 'Bill Weiss <github@houdini.spum.us>'
summary 'ClamAV module'
description 'This module is for configuring Clam Anti-Virus'
license 'This module is released under the MIT License'
project_page 'https://github.com/BillWeiss/puppet-clamav'
